'use client';

import Link from 'next/link';
import { ArrowRight, CircleDollarSign, LockKeyhole, ShieldCheck, Sparkles, UsersRound } from 'lucide-react';

const cards = [
  { href: '/deposit', label: 'Add money', detail: 'Deposit USDC and grow your shared position.', icon: CircleDollarSign, tone: 'mint' },
  { href: '/loans', label: 'Manage loans', detail: 'Review requests, repayments, and active borrowing.', icon: LockKeyhole, tone: 'peach' },
  { href: '/guarantees', label: 'Your guarantees', detail: 'See what you support and what is claimable.', icon: UsersRound, tone: 'lavender' },
];

export function DashboardPage() {
  return <main className="page finance-page dashboard-page"><section className="dashboard-intro"><div><span className="brand-kicker"><Sparkles size={14}/> MEMBER OVERVIEW</span><h1 className="section-title">Make progress<br/><span>together.</span></h1><p className="muted">Your chama at a glance. Choose one focused action to keep the group moving.</p></div><div className="health-orb"><ShieldCheck size={24}/><span>Healthy</span><small>Protocol status</small></div></section><section className="dashboard-metrics"><article className="metric-card primary-metric"><span>Community balance</span><strong>$0.00</strong><small>Connect a wallet to read live USDC</small></article><article className="metric-card"><span>Your shares</span><strong>—</strong><small>cUSDC position</small></article><article className="metric-card"><span>Available liquidity</span><strong>—</strong><small>Vault withdrawal capacity</small></article></section><section className="section dashboard-actions"><div className="section-head"><div><span className="eyebrow">QUICK ACTIONS</span><h2 className="section-title">Where do you want to go?</h2></div></div><div className="action-grid">{cards.map(({ href, label, detail, icon: Icon, tone }) => <Link className="action-card" href={href} key={href}><span className={`action-icon ${tone}`}><Icon size={20}/></span><span><strong>{label}</strong><small>{detail}</small></span><ArrowRight size={17}/></Link>)}</div></section><section className="section dashboard-note"><div className="card info-card"><div className="info-icon"><ShieldCheck size={19}/></div><div><strong>Built for transparent saving</strong><p className="muted">Balances, approvals, and activity are read from Arc. Every action that moves funds requires your wallet signature.</p></div><Link href="/health" className="text-button">View health <ArrowRight size={14}/></Link></div></section></main>;
}

export function GuaranteesPage() {
  return <main className="page finance-page simple-page"><section className="page-hero"><span className="brand-kicker"><UsersRound size={14}/> SHARED RESPONSIBILITY</span><h1 className="section-title">Guarantees</h1><p className="muted">Track the loans you back and the cUSDC that stays locked until repayment.</p></section><section className="stat-strip"><div><span>Locked shares</span><strong>—</strong></div><div><span>Active backing</span><strong>—</strong></div><div><span>Claimable interest</span><strong>—</strong></div></section><section className="section"><div className="section-head"><h2 className="section-title">Your backed loans</h2><span className="pill">No records</span></div><div className="card empty-panel"><div className="empty-icon"><UsersRound size={21}/></div><strong>Connect your wallet to continue</strong><p className="muted">Once connected, guarantees from the selected chama will appear here with risk and maturity details.</p><Link href="/loans" className="secondary">Browse loans <ArrowRight size={15}/></Link></div></section></main>;
}

export function SettingsPage() {
  return <main className="page finance-page simple-page"><section className="page-hero"><span className="brand-kicker"><Sparkles size={14}/> CONTROL CENTER</span><h1 className="section-title">Settings</h1><p className="muted">Review the network and contracts powering this chama.</p></section><section className="settings-list"><div className="card setting-row"><span className="setting-icon"><CircleDollarSign size={18}/></span><div><strong>Network</strong><small>Arc Testnet · Chain 5042002</small></div><span className="pill">Connected</span></div><div className="card setting-row"><span className="setting-icon"><ShieldCheck size={18}/></span><div><strong>Wallet security</strong><small>Transactions are signed by your connected wallet.</small></div><span className="pill">Self-custody</span></div><div className="card setting-row"><span className="setting-icon"><LockKeyhole size={18}/></span><div><strong>Contract data</strong><small>Addresses and balances are loaded from Arc.</small></div><Link href="/health" className="text-button">Inspect <ArrowRight size={14}/></Link></div></section></main>;
}
